# Generated by Django 4.2.3 on 2023-09-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
