# Generated by Django 4.2.3 on 2023-09-21 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("books_list", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookChapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chapter_name", models.CharField(max_length=100)),
                ("chapter_content", models.TextField()),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="books_list.book",
                    ),
                ),
            ],
        ),
    ]
