# Generated by Django 4.2.3 on 2023-09-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('star_rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('cover_image', models.ImageField(upload_to='book_covers/')),
                ('genres', models.ManyToManyField(to='books_list.genre')),
            ],
        ),
    ]
